package cems_project;

public enum BufferEnum {
    FORMIC_ACID_1M,
    AMMONIUM_ACETATE_50mM,
    FORMIC_ACID_0DOT26M,
    AMMONIUM_BICARBONATE_20mM,
    ACETIC_ACID_10PERCENT,
    FORMIC_ACID_0DOT5PERCENT_METHANOL_5PERCENT,
    AMMONIUM_BICARBONATE_50mM,
    AMMONIUM_ACETATE_50mM_METHANOL_5PERCENT,
    FORMIC_ACID_1M_ACN_15PERCENT,
// 35 mM ammonium acetate in 70 vol % acetonitrile, 15 vol % methanol, 10 vol % H2O, and 5 vol % 2-propanol
    AMMONIUM_ACETATE_35mM_ACETONITRILE_70PERCENT_METHANOL_15PERCENT_H2O_10PERCENT_2PROPANOL_5PERCENT,
    FORMIC_ACID_0DOT1M;
}
